# Generated by Django 4.2 on 2025-09-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_participante_clave_temporal'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='participante',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='participantes',
            field=models.ManyToManyField(related_name='proyectos', to='usuarios.participante'),
        ),
    ]
