# Generated by Django 3.2 on 2025-07-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_asistente'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='inscripciones_habilitadas',
            field=models.BooleanField(default=True),
        ),
    ]
