# Generated by Django 3.2 on 2025-07-03 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_evento_inscripciones_habilitadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('rubrica', 'Rúbrica'), ('chequeo', 'Lista de Chequeo'), ('plantilla', 'Plantilla')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='instrumentos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentos', to='eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='ItemInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='eventos.instrumentoevaluacion')),
            ],
        ),
    ]
