# Generated by Django 3.2 on 2025-07-03 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_rol'),
        ('eventos', '0005_instrumentoevaluacion_iteminstrumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluadorEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_asignados', to='usuarios.evaluador')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluadores_asignados', to='eventos.evento')),
            ],
            options={
                'unique_together': {('evaluador', 'evento')},
            },
        ),
    ]
