# Generated by Django 3.2 on 2025-07-06 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_documentoevaluador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentoEvaluador',
        ),
    ]
