# Generated by Django 3.2 on 2025-07-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_delete_documentoevaluador'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluadorevento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('admitido', 'Admitido'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
