# Generated by Django 3.2 on 2025-07-07 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_rol'),
        ('eventos', '0009_evaluadorevento_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoTecnicaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción técnica')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='info_tecnica_evento/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.evaluador')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_tecnica', to='eventos.evento')),
            ],
        ),
    ]
