# Generated by Django 4.2 on 2025-07-14 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_infotecnicaevento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCertificadoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(blank=True, max_length=255)),
                ('fecha_inicio_evento', models.DateField(blank=True, null=True)),
                ('fecha_fin_evento', models.DateField(blank=True, null=True)),
                ('lugar_evento', models.CharField(blank=True, max_length=255)),
                ('organizador_evento', models.CharField(blank=True, max_length=255)),
                ('mensaje_certificado', models.TextField(blank=True)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_certificado', to='eventos.evento')),
            ],
        ),
    ]
