# Generated by Django 5.2.4 on 2025-07-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_configuracioncertificadoevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminstrumento',
            name='peso_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Peso (%)'),
        ),
    ]
