# Generated by Django 4.2 on 2025-07-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_iteminstrumento_peso_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_eventos/'),
        ),
    ]
