# Generated by Django 4.2 on 2025-07-31 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_categoria_evento_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
    ]
