# Generated by Django 4.2 on 2025-07-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0016_remove_categoria_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
