# Generated by Django 4.2 on 2025-07-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0017_evento_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='inscripciones_asistente',
            field=models.BooleanField(default=True, verbose_name='Inscripciones habilitadas para asistentes'),
        ),
        migrations.AddField(
            model_name='evento',
            name='inscripciones_evaluador',
            field=models.BooleanField(default=True, verbose_name='Inscripciones habilitadas para evaluadores'),
        ),
        migrations.AddField(
            model_name='evento',
            name='inscripciones_participante',
            field=models.BooleanField(default=True, verbose_name='Inscripciones habilitadas para participantes'),
        ),
    ]
