# Generated by Django 4.2 on 2025-09-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0018_evento_inscripciones_asistente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado')], default='pendiente', max_length=20),
        ),
    ]
