# Generated by Django 4.2 on 2025-09-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0020_evento_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
