# Generated by Django 3.2 on 2025-06-30 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0003_delete_documentoparticipante'),
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos_participantes/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='inscripciones.inscripcionevento')),
            ],
        ),
    ]
