# Generated by Django 4.2 on 2025-09-06 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0021_alter_evento_estado'),
        ('proyectos', '0001_initial'),
        ('usuarios', '0007_participante_clave_temporal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=4)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.evaluador')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
            ],
            options={
                'unique_together': {('evaluador', 'proyecto')},
            },
        ),
        migrations.CreateModel(
            name='CalificacionParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.evaluador')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.instrumentoevaluacion')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.iteminstrumento')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.participante')),
            ],
            options={
                'unique_together': {('evaluador', 'participante', 'evento', 'instrumento', 'item')},
            },
        ),
    ]
