# Generated by Django 3.2 on 2025-06-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('participante', 'Participante'), ('evaluador', 'Evaluador'), ('asistente', 'Asistente'), ('admin_evento', 'Administrador de Evento')], max_length=20, null=True),
        ),
    ]
