# Generated by Django 3.2 on 2025-06-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradorevento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('admitido', 'Admitido'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='asistente',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('admitido', 'Admitido'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='evaluador',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('admitido', 'Admitido'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='participante',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('admitido', 'Admitido'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('participante', 'Participante'), ('evaluador', 'Evaluador'), ('asistente', 'Asistente'), ('admin_evento', 'Administrador de Evento'), ('super_admin', 'Super Admin')], max_length=20, null=True),
        ),
    ]
