# Generated by Django 3.2 on 2025-07-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20250630_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('participante', 'Participante'), ('evaluador', 'Evaluador'), ('asistente', 'Asistente'), ('admin', 'Administrador de Evento'), ('superadmin', 'Super Administrador')], max_length=20, null=True),
        ),
    ]
