# Generated by Django 4.2 on 2025-09-06 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAdminAccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('max_events', models.PositiveIntegerField(blank=True, help_text='Máximo número de eventos permitidos', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha/hora de expiración del código', null=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_access_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
