# Generated by Django 4.2 on 2025-09-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_eventadminaccesscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventadminaccesscode',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('cancelado', 'Cancelado')], default='activo', max_length=12),
        ),
    ]
