# Generated by Django 4.2 on 2025-09-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_eventadminaccesscode_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='clave_temporal',
            field=models.CharField(blank=True, help_text='Clave de acceso generada para el envío por correo al ser admitido.', max_length=128, null=True),
        ),
    ]
