# Generated by Django 3.2 on 2025-06-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0002_documentoparticipante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentoParticipante',
        ),
    ]
