# Generated by Django 3.2 on 2025-06-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0003_delete_documentoparticipante'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionevento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('admitido', 'Admitido'), ('no_admitido', 'No admitido')], default='pendiente', max_length=20),
        ),
    ]
