# Generated by Django 3.2 on 2025-06-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0004_inscripcionevento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionevento',
            name='clave_acceso',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
