# Generated by Django 3.2 on 2025-07-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0005_inscripcionevento_clave_acceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcionevento',
            name='clave_acceso',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
